name: CI/CD for Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Backend (Azure)
  backend-deploy:
    name: Deploy Backend to Azure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gaming-chat"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: back-end